version: 2.1
orbs:
  node: circleci/node@4.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - node/test:
          version: 15.11.0
      - deploy-job:
          requires:
            - node/test
          filters:
            branches:
              only: master

jobs:
  deploy-job:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Deploy job
          command: echo "whoami"
