name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the app
      run: |
        echo "Here is where you'd put your build commands!"

  test:
    name: Test
    needs: build
    runs_on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test the app
      run: |
        echo "Here is where you'd put your test commands!"
        
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy the app
      run: |
        echo "Here is where you'd put your deployment commands!"
